CREATE TABLE ASSESSMENT_PREDICTIONS (
    PREDICTION_ID NUMBER
        GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,

    ASSESSMENT_ID NUMBER NOT NULL,

    TALENT_LEVEL VARCHAR2(30) NOT NULL,

    CONFIDENCE NUMBER(6,4),

    RECOMMENDED_SPORT VARCHAR2(100),

    STRENGTHS VARCHAR2(1000),

    NEEDS_IMPROVEMENT VARCHAR2(1000),

    MODEL_VERSION VARCHAR2(50),

    CREATED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
        NOT NULL,

    CONSTRAINT FK_PREDICTION_ASSESSMENT
        FOREIGN KEY (ASSESSMENT_ID)
        REFERENCES ASSESSMENTS(ASSESSMENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT UQ_PREDICTION_ASSESSMENT
        UNIQUE (ASSESSMENT_ID)
);