CREATE TABLE ASSESSMENTS (
    ASSESSMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,

    USER_ID NUMBER NOT NULL,

    STATUS VARCHAR2(20) DEFAULT 'CREATED' NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    COMPLETED_AT TIMESTAMP,

    CONSTRAINT FK_ASSESSMENT_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USER_DETAILS(USERID),

    CONSTRAINT CHK_ASSESSMENT_STATUS
        CHECK (STATUS IN (
            'CREATED',
            'IN_PROGRESS',
            'COMPLETED',
            'FAILED'
        ))
);