CREATE TABLE ASSESSMENT_CV_LINK (
    LINK_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    ASSESSMENT_ID NUMBER NOT NULL,
    SESSION_ID NUMBER NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT FK_ACL_ASSESSMENT
        FOREIGN KEY (ASSESSMENT_ID)
        REFERENCES ASSESSMENTS(ASSESSMENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_ACL_SESSION
        FOREIGN KEY (SESSION_ID)
        REFERENCES CV_SESSION_RESULTS(SESSION_ID)
        ON DELETE CASCADE
);