CREATE TABLE ASSESSMENT_FEATURE_SNAPSHOT (
    SNAPSHOT_ID NUMBER
        GENERATED ALWAYS AS IDENTITY
        PRIMARY KEY,

    ASSESSMENT_ID NUMBER NOT NULL,

    AGE NUMBER(3,0) NOT NULL,
    GENDER VARCHAR2(10) NOT NULL,
    HEIGHT_CM NUMBER(6,2) NOT NULL,
    WEIGHT_KG NUMBER(6,2) NOT NULL,

    PUSHUP_COUNT NUMBER(6,2) NOT NULL,
    SQUAT_COUNT NUMBER(6,2) NOT NULL,
    DEADLIFT_REPS NUMBER(6,2) NOT NULL,
    RUNNING_50M_SECONDS NUMBER(6,2) NOT NULL,
    SITUP_COUNT NUMBER(6,2) NOT NULL,
    PLANK_DURATION_SECONDS NUMBER(8,2) NOT NULL,
    VERTICAL_JUMP_CM NUMBER(6,2) NOT NULL,

    CREATED_AT TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
        NOT NULL,

    CONSTRAINT FK_FEATURE_SNAPSHOT_ASSESSMENT
        FOREIGN KEY (ASSESSMENT_ID)
        REFERENCES ASSESSMENTS(ASSESSMENT_ID)
        ON DELETE CASCADE,

    CONSTRAINT UQ_FEATURE_SNAPSHOT_ASSESSMENT
        UNIQUE (ASSESSMENT_ID)
);