WITH ranked_results AS (
    SELECT
        ACL.ASSESSMENT_ID,
        CSR.SESSION_ID,
        CSR.TEST_NAME,
        CM.FEATURE_NAME,
        CM.FEATURE_VALUE,
        ROW_NUMBER() OVER (
            PARTITION BY CSR.TEST_NAME
            ORDER BY CSR.SESSION_ID DESC
        ) AS rn
    FROM ASSESSMENT_CV_LINK ACL
    JOIN CV_SESSION_RESULTS CSR
        ON CSR.SESSION_ID = ACL.SESSION_ID
    JOIN CV_MEASUREMENTS CM
        ON CM.SESSION_ID = CSR.SESSION_ID
    WHERE ACL.ASSESSMENT_ID = 1
      AND CSR.STATUS = 'SUCCESS'
      AND CM.FEATURE_VALUE IS NOT NULL
)
SELECT
    SESSION_ID,
    TEST_NAME,
    FEATURE_NAME,
    FEATURE_VALUE
FROM ranked_results
WHERE rn = 1
ORDER BY TEST_NAME;