--------------------------------------------------------
--  File created - Saturday-September-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATHLETE_DATA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ATHLETE_DATA" 
   (	"ATHLETE_ID" VARCHAR2(50 BYTE), 
	"AGE" NUMBER(3,0), 
	"GENDER" VARCHAR2(10 BYTE), 
	"HEIGHT_CM" NUMBER(5,2), 
	"WEIGHT_KG" NUMBER(5,2), 
	"PUSHUP_COUNT" NUMBER(5,0) DEFAULT 0, 
	"SQUAT_COUNT" NUMBER(5,0) DEFAULT 0, 
	"DEADLIFT_REPS" NUMBER(5,0) DEFAULT 0, 
	"RUNNING_50M_SECONDS" NUMBER(5,2), 
	"SITUP_COUNT" NUMBER(5,0) DEFAULT 0, 
	"PLANK_DURATION_SECONDS" NUMBER(6,2) DEFAULT 0, 
	"VERTICAL_JUMP_CM" NUMBER(5,2) DEFAULT 0, 
	"TALENT_LEVEL" VARCHAR2(20 BYTE), 
	"RECOMMENDED_SPORT" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."ATHLETE_ID" IS 'Unique ID assigned to the athlete';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."AGE" IS 'Age in years (5 - 100)';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."GENDER" IS 'Gender category (Male/Female/Other)';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."HEIGHT_CM" IS 'Height in centimeters';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."WEIGHT_KG" IS 'Weight in kilograms';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."PUSHUP_COUNT" IS 'Total completed push-up reps';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."SQUAT_COUNT" IS 'Total completed squat reps';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."DEADLIFT_REPS" IS 'Total deadlift reps at standard load';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."RUNNING_50M_SECONDS" IS 'Time taken for 50m sprint in seconds';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."SITUP_COUNT" IS 'Total completed sit-up reps';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."PLANK_DURATION_SECONDS" IS 'Plank hold duration in seconds';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."VERTICAL_JUMP_CM" IS 'Vertical jump height in centimeters';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."TALENT_LEVEL" IS 'Target predicted talent level';
   COMMENT ON COLUMN "SYSTEM"."ATHLETE_DATA"."RECOMMENDED_SPORT" IS 'Target recommended sport based on performance profile';
REM INSERTING into SYSTEM.ATHLETE_DATA
SET DEFINE OFF;
Insert into SYSTEM.ATHLETE_DATA (ATHLETE_ID,AGE,GENDER,HEIGHT_CM,WEIGHT_KG,PUSHUP_COUNT,SQUAT_COUNT,DEADLIFT_REPS,RUNNING_50M_SECONDS,SITUP_COUNT,PLANK_DURATION_SECONDS,VERTICAL_JUMP_CM,TALENT_LEVEL,RECOMMENDED_SPORT) values ('ATH-1001',19,'Male',178.5,72,55,75,22,6.4,60,300,68.5,'Elite','Athletics (Sprinting)');
Insert into SYSTEM.ATHLETE_DATA (ATHLETE_ID,AGE,GENDER,HEIGHT_CM,WEIGHT_KG,PUSHUP_COUNT,SQUAT_COUNT,DEADLIFT_REPS,RUNNING_50M_SECONDS,SITUP_COUNT,PLANK_DURATION_SECONDS,VERTICAL_JUMP_CM,TALENT_LEVEL,RECOMMENDED_SPORT) values ('ATH-1002',22,'Female',165,58.5,28,42,12,8.1,35,120,42,'Intermediate','Badminton');
Insert into SYSTEM.ATHLETE_DATA (ATHLETE_ID,AGE,GENDER,HEIGHT_CM,WEIGHT_KG,PUSHUP_COUNT,SQUAT_COUNT,DEADLIFT_REPS,RUNNING_50M_SECONDS,SITUP_COUNT,PLANK_DURATION_SECONDS,VERTICAL_JUMP_CM,TALENT_LEVEL,RECOMMENDED_SPORT) values ('ATH-1003',16,'Male',160,50,12,20,5,9.8,18,45,30,'Beginner','General Fitness Training');
--------------------------------------------------------
--  DDL for Index SYS_C008642
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008642" ON "SYSTEM"."ATHLETE_DATA" ("ATHLETE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATHLETE_DATA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ATHLETE_DATA" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" MODIFY ("HEIGHT_CM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" MODIFY ("WEIGHT_KG" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (AGE BETWEEN 5 AND 100) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (GENDER IN ('Male', 'Female', 'Other')) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (HEIGHT_CM BETWEEN 80 AND 250) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (WEIGHT_KG BETWEEN 20 AND 300) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (PUSHUP_COUNT BETWEEN 0 AND 200) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (SQUAT_COUNT BETWEEN 0 AND 300) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (DEADLIFT_REPS BETWEEN 0 AND 100) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (RUNNING_50M_SECONDS BETWEEN 3 AND 30) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (SITUP_COUNT BETWEEN 0 AND 200) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (PLANK_DURATION_SECONDS BETWEEN 0 AND 1800) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (VERTICAL_JUMP_CM BETWEEN 0 AND 150) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD CHECK (TALENT_LEVEL IN ('Beginner', 'Intermediate', 'Advanced', 'Elite')) ENABLE;
  ALTER TABLE "SYSTEM"."ATHLETE_DATA" ADD PRIMARY KEY ("ATHLETE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
