--------------------------------------------------------
--  File created - Saturday-September-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CV_FEATURE_METRICS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CV_FEATURE_METRICS" 
   (	"METRIC_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SESSION_ID" NUMBER, 
	"ELBOW_ANGLE" NUMBER(6,2), 
	"BODY_ANGLE" NUMBER(6,2), 
	"BODY_HORIZONTAL_ANGLE" NUMBER(6,2), 
	"KNEE_ANGLE" NUMBER(6,2), 
	"TORSO_LEAN" NUMBER(6,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."CV_FEATURE_METRICS"."METRIC_ID" IS 'Auto-generated primary key for individual metric log entries';
REM INSERTING into SYSTEM.CV_FEATURE_METRICS
SET DEFINE OFF;
Insert into SYSTEM.CV_FEATURE_METRICS (METRIC_ID,SESSION_ID,ELBOW_ANGLE,BODY_ANGLE,BODY_HORIZONTAL_ANGLE,KNEE_ANGLE,TORSO_LEAN) values (1,1,170.68,172.76,89.35,175.2,5.1);
Insert into SYSTEM.CV_FEATURE_METRICS (METRIC_ID,SESSION_ID,ELBOW_ANGLE,BODY_ANGLE,BODY_HORIZONTAL_ANGLE,KNEE_ANGLE,TORSO_LEAN) values (2,2,165,158.4,45.2,141.8,22.4);
--------------------------------------------------------
--  DDL for Index SYS_C008653
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008653" ON "SYSTEM"."CV_FEATURE_METRICS" ("METRIC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CV_FEATURE_METRICS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CV_FEATURE_METRICS" MODIFY ("METRIC_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CV_FEATURE_METRICS" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CV_FEATURE_METRICS" ADD PRIMARY KEY ("METRIC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CV_FEATURE_METRICS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CV_FEATURE_METRICS" ADD CONSTRAINT "FK_METRIC_SESSION" FOREIGN KEY ("SESSION_ID")
	  REFERENCES "SYSTEM"."CV_SESSION_RESULTS" ("SESSION_ID") ON DELETE CASCADE ENABLE;
