--------------------------------------------------------
--  File created - Saturday-September-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CV_SESSION_RESULTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CV_SESSION_RESULTS" 
   (	"SESSION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TEST_NAME" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'SUCCESS', 
	"INPUT_SOURCE" VARCHAR2(20 BYTE), 
	"PERSON_DETECTED" NUMBER(1,0), 
	"FRAMES_PROCESSED" NUMBER(8,0) DEFAULT 0, 
	"PERSON_FRAMES" NUMBER(8,0) DEFAULT 0, 
	"INVALID_FRAMES" NUMBER(8,0) DEFAULT 0, 
	"LAST_STAGE" VARCHAR2(50 BYTE), 
	"LAST_FRAME_VALID_POSTURE" NUMBER(1,0), 
	"VALID_REPS" NUMBER(5,0) DEFAULT 0, 
	"TEST_TIMESTAMP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP -- ISO timestamp when session was executed

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."CV_SESSION_RESULTS"."SESSION_ID" IS 'Auto-generated sequence ID uniquely identifying the CV session';
REM INSERTING into SYSTEM.CV_SESSION_RESULTS
SET DEFINE OFF;
Insert into SYSTEM.CV_SESSION_RESULTS (SESSION_ID,TEST_NAME,STATUS,INPUT_SOURCE,PERSON_DETECTED,FRAMES_PROCESSED,PERSON_FRAMES,INVALID_FRAMES,LAST_STAGE,LAST_FRAME_VALID_POSTURE,VALID_REPS,TEST_TIMESTAMP) values (1,'pushup','SUCCESS','webcam',1,1543,1543,245,'INVALID_POSTURE',0,6,to_timestamp('05-09-26 12:48:56.551000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SYSTEM.CV_SESSION_RESULTS (SESSION_ID,TEST_NAME,STATUS,INPUT_SOURCE,PERSON_DETECTED,FRAMES_PROCESSED,PERSON_FRAMES,INVALID_FRAMES,LAST_STAGE,LAST_FRAME_VALID_POSTURE,VALID_REPS,TEST_TIMESTAMP) values (2,'squat','SUCCESS','video',1,1674,1674,80,'VALID_POSTURE',1,15,to_timestamp('05-09-26 12:48:56.567000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
Insert into SYSTEM.CV_SESSION_RESULTS (SESSION_ID,TEST_NAME,STATUS,INPUT_SOURCE,PERSON_DETECTED,FRAMES_PROCESSED,PERSON_FRAMES,INVALID_FRAMES,LAST_STAGE,LAST_FRAME_VALID_POSTURE,VALID_REPS,TEST_TIMESTAMP) values (3,'running','FAILED','video',0,450,120,330,'PERSON_NOT_FOUND',0,0,to_timestamp('05-09-26 12:48:56.574000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
--------------------------------------------------------
--  DDL for Index SYS_C008650
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008650" ON "SYSTEM"."CV_SESSION_RESULTS" ("SESSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CV_SESSION_RESULTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CV_SESSION_RESULTS" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CV_SESSION_RESULTS" MODIFY ("TEST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."CV_SESSION_RESULTS" ADD CHECK (TEST_NAME IN ('pushup', 'squat', 'deadlift', 'running', 'situp', 'plank', 'vertical_jump')) ENABLE;
  ALTER TABLE "SYSTEM"."CV_SESSION_RESULTS" ADD CHECK (STATUS IN ('SUCCESS', 'FAILED')) ENABLE;
  ALTER TABLE "SYSTEM"."CV_SESSION_RESULTS" ADD CHECK (INPUT_SOURCE IN ('webcam', 'video')) ENABLE;
  ALTER TABLE "SYSTEM"."CV_SESSION_RESULTS" ADD CHECK (PERSON_DETECTED IN (0, 1)) ENABLE;
  ALTER TABLE "SYSTEM"."CV_SESSION_RESULTS" ADD CHECK (LAST_FRAME_VALID_POSTURE IN (0, 1)) ENABLE;
  ALTER TABLE "SYSTEM"."CV_SESSION_RESULTS" ADD PRIMARY KEY ("SESSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
