--------------------------------------------------------
--  File created - Saturday-September-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EXERCISE_FORM_FEATURES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EXERCISE_FORM_FEATURES" 
   (	"FORM_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EXERCISE_TYPE" VARCHAR2(30 BYTE), 
	"FORM_LABEL" VARCHAR2(20 BYTE), 
	"CONFIDENCE_SCORE" NUMBER(5,4), 
	"EVALUATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP -- Timestamp of form prediction

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "SYSTEM"."EXERCISE_FORM_FEATURES"  IS 'Tracks exercise form analysis results and model evaluation outputs separately from talent levels.';
REM INSERTING into SYSTEM.EXERCISE_FORM_FEATURES
SET DEFINE OFF;
Insert into SYSTEM.EXERCISE_FORM_FEATURES (FORM_ID,EXERCISE_TYPE,FORM_LABEL,CONFIDENCE_SCORE,EVALUATED_AT) values (1,'vertical_jump','Uncertain',0.45,to_timestamp('05-09-26 12:51:07.619000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
--------------------------------------------------------
--  DDL for Index SYS_C008661
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008661" ON "SYSTEM"."EXERCISE_FORM_FEATURES" ("FORM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EXERCISE_FORM_FEATURES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EXERCISE_FORM_FEATURES" MODIFY ("FORM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EXERCISE_FORM_FEATURES" MODIFY ("EXERCISE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EXERCISE_FORM_FEATURES" MODIFY ("FORM_LABEL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."EXERCISE_FORM_FEATURES" ADD CHECK (EXERCISE_TYPE IN ('pushup', 'squat', 'deadlift', 'running', 'situp', 'plank', 'vertical_jump')) ENABLE;
  ALTER TABLE "SYSTEM"."EXERCISE_FORM_FEATURES" ADD CHECK (FORM_LABEL IN ('Correct', 'Incorrect', 'Uncertain')) ENABLE;
  ALTER TABLE "SYSTEM"."EXERCISE_FORM_FEATURES" ADD CHECK (CONFIDENCE_SCORE BETWEEN 0 AND 1) ENABLE;
  ALTER TABLE "SYSTEM"."EXERCISE_FORM_FEATURES" ADD PRIMARY KEY ("FORM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
