--------------------------------------------------------
--  File created - Saturday-September-05-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MODEL_METADATA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MODEL_METADATA" 
   (	"MODEL_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MODEL_VERSION" VARCHAR2(20 BYTE) DEFAULT '1.2.0', 
	"RANDOM_STATE" NUMBER(5,0) DEFAULT 42, 
	"CONTRACT_VERSION" VARCHAR2(10 BYTE) DEFAULT '2.0', 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP -- Timestamp of model version deployment or update

   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."MODEL_METADATA"."MODEL_ID" IS 'Auto-generated primary key identifying the model configuration entry';
REM INSERTING into SYSTEM.MODEL_METADATA
SET DEFINE OFF;
Insert into SYSTEM.MODEL_METADATA (MODEL_ID,MODEL_VERSION,RANDOM_STATE,CONTRACT_VERSION,UPDATED_AT) values (1,'1.3.0',100,'2.1',to_timestamp('05-09-26 12:51:19.045000000 PM','DD-MM-RR fmHH12:fmMI:SSXFF AM'));
--------------------------------------------------------
--  DDL for Index SYS_C008666
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C008666" ON "SYSTEM"."MODEL_METADATA" ("MODEL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MODEL_METADATA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MODEL_METADATA" MODIFY ("MODEL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODEL_METADATA" MODIFY ("MODEL_VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODEL_METADATA" MODIFY ("RANDOM_STATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODEL_METADATA" MODIFY ("CONTRACT_VERSION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MODEL_METADATA" ADD PRIMARY KEY ("MODEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
