create or replace NONEDITIONABLE PACKAGE USER_MANAGEMENT AS 

PROCEDURE INSERT_USER_DETAILS (
        P_ROLE         IN  USER_DETAILS.ROLE%TYPE,
        P_FNM          IN  USER_DETAILS.FNM%TYPE,
        P_LNM          IN  USER_DETAILS.LNM%TYPE,
        P_MOB_NO       IN  USER_DETAILS.MOB_NO%TYPE,
        P_AGE          IN  USER_DETAILS.AGE%TYPE,
        P_GENDER       IN  USER_DETAILS.GENDER%TYPE,
        P_USERNAME     IN  USER_DETAILS.USERNAME%TYPE,
        P_PASSWORD     IN  USER_DETAILS.PASSWORD%TYPE,
        P_ADDR_LINE_1  IN  USER_DETAILS.ADDR_LINE_1%TYPE DEFAULT NULL,
        P_DIST         IN  USER_DETAILS.DIST%TYPE        DEFAULT NULL,
        P_PSTL_CD      IN  USER_DETAILS.PSTL_CD%TYPE     DEFAULT NULL,
        P_STATE        IN  USER_DETAILS.STATE%TYPE       DEFAULT NULL,
        P_COUNTRY      IN  USER_DETAILS.COUNTRY%TYPE     DEFAULT 'INDIA',
        P_WGT          IN  USER_DETAILS.WGT%TYPE         DEFAULT NULL,
        P_HGT          IN  USER_DETAILS.HGT%TYPE         DEFAULT NULL,
        O_STATUS       OUT VARCHAR2,
        O_MESSAGE      OUT VARCHAR2
);
END USER_MANAGEMENT;